name: Bug Report
description: File a bug report.
labels: ["bug"]
# assignees:
# projects:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: (Only put images in here)
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: What operating software are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - MacOS
        - Windows
        - iOS
        - Android
        - Other
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: dropdown
    id: version
    attributes:
      label: What app are you seeing the problem on?
      options:
        - The House App
        - The Grades App
        - The Questions App
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Lastly, add any other context about the problem here.
    validations:
      required: false
